---

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'git', 'python3-setuptools', 'gnupg', 'lsb-release']

- name: Add Docker GPG apt Key
  shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'

- name: Add Docker Repository
  shell: 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian buster stable" | tee /etc/apt/sources.list.d/docker.list'


- name: Update apt and install docker-ce
  apt: update_cache=yes {{ item }} state=latest
  loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Install Docker Module for Python
  pip:
    name: docker

